spring:
  profiles:
    active:  prod
  application:
    name:  PRODUCT-APP
  config:
    import:  optional:configserver:http://localhost:8082/management.endpoints.web.exposure.include=refresh
server:
  port:  7070