## HSQLDB In-Memory Configuration
#spring.datasource.url=jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
#spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=create # or update, validate, none

#  h2 sql profile for development
spring:
  h2:
    console:
      enabled:  true
  datasource:
    username:  sa
    password:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url:  jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1

  jpa:
    hibernate:
      ddl-auto:  create
    show-sql:  true
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.HSQLDialect

server:
  port:  5050