#  h2 sql profile for development
spring:
  h2:
    console:
      enabled:  true
  datasource:
    username:  sa
    password:
    driver-class-name: org.h2.Driver
    url:  jdbc:h2:mem:testdb

  jpa:
    hibernate:
      ddl-auto:  create
    show-sql:  true
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.H2Dialect

server:
  port:  7070