#spring.main.web-application-type=reactive
server:
  port:  7575
spring:
  main:
    web-application-type:  reactive
  application:
    name:  api-gateway
  cloud:
    gateway:
      routes:
        - id:  PRODUCT-APP
          uri:  http://localhost:7070
          predicates:
           - Path=/product/**
#           - Path=/product1/**

        - id:  PRODUCT-ORDER-APP
          uri:  http://localhost:9090
          predicates:
            - Path=/order/**

        - id:  product-payment-app
          uri:  http://localhost:9092
          predicates:
            - Path=/payment/**